"""empty message

Revision ID: 0fc90a19b990
Revises: 
Create Date: 2019-04-04 17:05:33.474252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc90a19b990'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('common', sa.Boolean(), nullable=True))
    op.add_column('models', sa.Column('project', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'models', 'projects', ['project'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'project')
    op.drop_column('models', 'common')
    # ### end Alembic commands ###
